name: Test JavaScript Package

on:
  push:
    branches: [main]
    paths: 'typescript/**'
  pull_request:
    paths: 'typescript/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./typescript

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: true
          cache-dependency-path: ./typescript/package-lock.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm test
