name: Publish JavaScript Package

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./typescript

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          architecture: x64
      - run: npm ci
      - run: npm test

  publish-npm:
    name: Upload release to NPM
    needs: build
    runs-on: ubuntu-latest
    environment: npm-release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          architecture: x64
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
