name: Publish Python Package

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          pathon-version: 3.10
          architecture: x64

      - name: Publish package distributions to PyPI
        working-directory: ./python
        run: pdm publish
