name: Python Tests

on:
  push:
    branches: [main]
    paths: 'python/**'
  pull_request:
    paths: 'python/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./python

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: ./python/pdm.lock

      - name: Install dependencies
        run: |
          python -m pip install --upgrade tox .

      - name: Test with tox
        run: |
          tox --version
          pyversion="${{ matrix.python-version }}"
          tox -e py${pyversion/./}
