name: Publish Python Package

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./python

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: python-release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Publish package distributions to PyPI
        run: pdm publish
